version = 1

exclude_patterns = [
    "package.json",
    "src/header.js"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  style_guide = "standard"

[[transformers]]
name = "prettier"
enabled = true
