version = 1

exclude_patterns = [
    "package.json",
    "src/header.js",
    "dist/**",
    "minify.js",
    "docs/**",
    "*.md"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]

[[transformers]]
name = "prettier"
enabled = true
